[[pages]]
path = "app_pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Chatbot Projects"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "app_pages/my_chat_bot.py"
name = "My Chat Bot"
icon = ":robot_face:"

[[pages]]
path = "app_pages/ask_to_youtube.py"
name = "Ask to Youtube"
icon = ":clown_face:"
