[[pages]]
path = "pages/00_home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Chatbot Projects"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "pages/01_my_chat_bot.py"
name = "My Chat Bot"
icon = ":robot_face:"

[[pages]]
path = "pages/02_ask_to_youtube.py"
name = "Ask to Youtube"
icon = ":clown_face:"
